### ISSUE TITLE
Isn't mailing. Unhelpful error.

### ISSUE THREAD

**Issue by Fabio-RibeiroB** [bradymd/freecertiffy#1]
After clicking mail, I get the "There is no contact to mail", despite the Contact field filled out with my email.

I have filled out my email in dist/myenv-dist.env but left SMTPHOST as default.

**Comment by bradymd** [comment]
Thanks Fabio. I had indeed introduced some bad code there.r  read_record_db(cert) returns a list of records so result['contact'] was not right.
